### ISSUE TITLE
result of control_transfer

### ISSUE THREAD

**Issue by tcurdt** [larskanis/libusb#18] opened 2015-08-25 20:04 UTC
Based on the docs I came up with this code

```
require "libusb"

usb = LIBUSB::Context.new

device = usb.devices(:idVendor => 0x16d0, :idProduct => 0x0753).first

raise "device not found" if device.nil?

device.open_interface(0) do |handle|
  handle.control_transfer({
    :bmRequestType => LIBUSB::ENDPOINT_IN|LIBUSB::REQUEST_TYPE_CLASS|LIBUSB::RECIPIENT_INTERFACE,
    :bRequest => 0x01,
    :wIndex => 0,
    :wValue => 0,
    :dataIn => 1,
    :timeout => 0
  }) do |result|
    puts "result #{result}"
  end
end
```

but it never returns.
Does the libusb gem require eventmachine? or what am I doing wrong?

**Comment by larskanis** [comment] 2015-08-26 09:10
If `DevHandle#control_transfer` is called with a block, then the transfer will be started asynchronously and will run in the background. Therefore `Context#handle_events` must be called properly, so that the transfer can be completed.

However you probably want to start the control transfer in a blocking manner. So you should call:
```
result = handle.control_transfer(...)
puts "result #{result}"
```

> Does the libusb gem require eventmachine?

libusb gem has some EventMachine-support, but this is optional and not active per default.

**Comment by tcurdt** [comment] 2015-08-26 10:14
Thanks for the clarification, @larskanis.

Like this it returns immediately - but the result is just an empty string.

    device.open_interface(0) do |handle|
      loop do
        result = handle.control_transfer({
          :bmRequestType => LIBUSB::ENDPOINT_IN|LIBUSB::REQUEST_TYPE_CLASS|LIBUSB::RECIPIENT_INTERFACE,
          :bRequest => 0x01,
          :wIndex => 0,
          :wValue => 0,
          :dataIn => 1,
          :timeout => 0
        })
        puts "result '#{result}' [#{result.class}]"
      end
    end

Might be that the request is wrong (I will check with the manufacturer).
But with `dataIn => 1` shouldn't there be at least one byte?

**Comment by larskanis** [comment] 2015-08-26 11:55
> But with dataIn => 1 shouldn't there be at least one byte?

With `dataIn => 1` you send a request for one byte, but if you get an empty string back, the device returned zero bytes only. You need to check with the manufacturer or use the USB/device documentation. Unfortunately I'm no expert regarding the USB protocol.

**Comment by tcurdt** [comment] 2015-08-26 21:21
...but without a timeout it should wait forever (until there is one byte), no?
Why would it return with zero bytes?

**Comment by larskanis** [comment] 2015-10-26 12:47
@tcurdt Could you solve your USB issue?

**Comment by tcurdt** [comment] 2015-10-26 12:50
I found a non-ruby way that works. I could try it again now in ruby - just for the fun of it.

**Comment by larskanis** [comment] 2015-10-26 15:45
I just googled for your USB device ids and found the following ruby implementation for it [here](https://github.com/Bluebie/littlewire.rb/blob/master/lib/littlewire/gadgets/micronucleus.rb) . Is it your device?

**Comment by tcurdt** [comment] 2015-10-26 15:58
It's the digispark pro http://digistump.com/products/109
http://digistump.com/wiki/digispark/tutorials/debugging

I was trying to get gem working https://rubygems.org/gems/digiusb/versions/1.0.5 which is at https://github.com/Bluebie/digiusb.rb

Since that didn't work so well I thought I give it try directly.

**Comment by larskanis** [comment] 2016-12-03 21:09
Closing, since the issue is probably solved in the meantime.

**Closed by larskanis** 2016-12-03 21:09 UTC
